
const C=window.GDR_CONFIG;
let token=localStorage.getItem('gdr360_token')||'', user=JSON.parse(localStorage.getItem('gdr360_user')||'null');
let state={athletes:[],trainings:[],records:[],games:[],callups:[],users:[]}, view='home', draft=null;

const $=id=>document.getElementById(id);
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=p=>p+Math.random().toString(36).slice(2,8)+Date.now().toString(36);
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-PT');
const admin=()=>user?.role==='admin';
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
async function api(action,payload={}){
 if(!C.API_URL) throw new Error('API_URL ainda não configurado em config.js');
 const r=await fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,...payload})});
 const j=await r.json(); if(!j.ok) throw new Error(j.error||'Erro na API'); return j;
}
function avatar(a,size=''){return `<div class="avatar">${a.photoUrl?`<img src="${esc(a.photoUrl)}" alt="">`:esc(a.name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase())}</div>`}
function loginScreen(err=''){return `<div class="login-page"><div class="login-card"><img class="login-logo" src="logo-formacao-gdr.png"><h1>GDR Formação 360</h1><p>Área reservada à equipa técnica</p>${err?`<div class="error">${esc(err)}</div>`:''}<div class="field"><label>Utilizador</label><input id="lu" autocomplete="username"></div><div class="field"><label>PIN</label><input id="lp" class="pin" type="password" inputmode="numeric" maxlength="8"></div><button class="btn btn-primary btn-block" onclick="login()">Entrar</button></div></div>`}
async function login(){try{const j=await api('login',{username:$('lu').value,pin:$('lp').value});token=j.token;user=j.user;localStorage.setItem('gdr360_token',token);localStorage.setItem('gdr360_user',JSON.stringify(user));await refresh();view='home';render()}catch(e){$('app').innerHTML=loginScreen(e.message)}}
function logout(){token='';user=null;localStorage.removeItem('gdr360_token');localStorage.removeItem('gdr360_user');render()}
async function refresh(){const j=await api('getData');state=j.data}
function nav(){return `<nav class="nav">${[['home','⌂','Início'],['training','⚽','Treino'],['athletes','👥','Atletas'],['callup','📋','Convocar'],['dashboard','📊','Dashboard']].map(([v,i,t])=>`<button class="${view===v?'active':''}" onclick="go('${v}')"><span class="ico">${i}</span>${t}</button>`).join('')}</nav>`}
function shell(body){return `<div class="app"><header class="topbar"><div class="brand"><img class="brand-logo" src="logo-formacao-gdr.png"><div class="brand-copy"><h1>${C.APP_NAME}</h1><small>${esc(user.name)}</small></div><span class="role">${admin()?'Administrador':'Treinador'}</span><button class="logout" onclick="logout()">Sair</button></div></header><main class="content">${body}</main>${nav()}</div>`}
function go(v){view=v;draft=null;render()}
function attendancePct(id){const r=state.records.filter(x=>x.athleteId===id);return r.length?Math.round(r.filter(x=>x.status==='Presente').length/r.length*100):0}
function avg(id,k){const r=state.records.filter(x=>x.athleteId===id&&x.status==='Presente'&&Number(x[k]));return r.length?r.reduce((s,x)=>s+Number(x[k]),0)/r.length:0}
function score(a){return Math.round(attendancePct(a.id)*.35+avg(a.id,'effort')*20*.30+avg(a.id,'attitude')*20*.20+avg(a.id,'behavior')*20*.15)}
function home(){const aa=state.athletes.filter(a=>a.active);const rec=state.records,p=rec.filter(x=>x.status==='Presente').length;return `<section class="hero"><h2>Olá, ${esc(user.name)} 👋</h2><div class="muted">Registo rápido de treino e acompanhamento da formação.</div></section><div class="grid"><div class="card kpi"><span>Atletas</span><strong>${aa.length}</strong></div><div class="card kpi"><span>Treinos</span><strong>${state.trainings.length}</strong></div><div class="card kpi"><span>Assiduidade</span><strong>${rec.length?Math.round(p/rec.length*100):0}%</strong></div><div class="card kpi"><span>Jogos</span><strong>${state.games.length}</strong></div></div><div class="section"><h3>Ações rápidas</h3></div><div class="list"><button class="btn btn-primary btn-block" onclick="go('training')">⚡ Registar treino</button><button class="btn btn-secondary btn-block" onclick="go('callup')">📋 Preparar convocatória</button><button class="btn btn-secondary btn-block" onclick="go('athletes')">👥 ${admin()?'Gerir':'Ver'} atletas</button>${admin()?'<button class="btn btn-secondary btn-block" onclick="view=\'users\';render()">🔐 Gerir utilizadores</button>':''}</div>`}
function athletes(){const aa=state.athletes.filter(a=>a.active);return `<div class="section"><h3>Atletas</h3>${admin()?'<button class="btn btn-primary" onclick="athleteForm()">+ Adicionar</button>':''}</div>${!admin()?'<div class="admin-note">🔒 O treinador pode consultar os atletas. Adicionar, editar e eliminar é exclusivo do Administrador.</div>':''}<div class="list">${aa.map(a=>`<div class="card athlete">${avatar(a)}<div class="grow"><strong>${esc(a.name)}</strong><div class="muted">${esc(a.group)} · ${attendancePct(a.id)}% presença</div></div>${admin()?`<div class="actions"><button class="btn btn-small btn-ghost" onclick="athleteForm('${a.id}')">Editar</button><button class="btn btn-small btn-danger" onclick="deleteAthlete('${a.id}')">Eliminar</button></div>`:''}</div>`).join('')}</div>`}
function athleteForm(id=''){if(!admin())return;const a=id?state.athletes.find(x=>x.id===id):null;view='athleteForm';$('app').innerHTML=shell(`<div class="section"><h3>${a?'Editar':'Novo'} atleta</h3></div><div class="card"><div class="photo-preview" id="photoPreview">${a?.photoUrl?`<img src="${esc(a.photoUrl)}">`:'Sem foto'}</div><div class="field"><label>Fotografia</label><input id="aphoto" type="file" accept="image/*" capture="environment" onchange="previewPhoto(this)"><div class="muted">A imagem será reduzida automaticamente antes do envio.</div></div><div class="field"><label>Nome</label><input id="aname" value="${esc(a?.name||'')}"></div><div class="field"><label>Escalão</label><select id="agroup"><option ${a?.group==='Benjamins'?'selected':''}>Benjamins</option><option ${a?.group==='Traquinas'?'selected':''}>Traquinas</option><option ${a?.group==='Traquinas/Benjamins'?'selected':''}>Traquinas/Benjamins</option></select></div><button class="btn btn-primary btn-block" onclick="saveAthlete('${id}')">Guardar atleta</button></div>`)}
function previewPhoto(inp){const f=inp.files[0];if(!f)return;const u=URL.createObjectURL(f);$('photoPreview').innerHTML=`<img src="${u}">`}
async function resizePhoto(file){return new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{let w=img.width,h=img.height,max=520;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>=w&&h>max){w=Math.round(w*max/h);h=max}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.78))};img.onerror=rej;img.src=u})}
async function saveAthlete(id){try{const file=$('aphoto').files[0];let photoBase64='';if(file)photoBase64=await resizePhoto(file);await api('saveAthlete',{athlete:{id,name:$('aname').value.trim(),group:$('agroup').value},photoBase64});await refresh();view='athletes';render();toast('Atleta guardado')}catch(e){toast(e.message)}}
async function deleteAthlete(id){if(!confirm('Remover este atleta da lista ativa?'))return;try{await api('deleteAthlete',{id});await refresh();render();toast('Atleta removido')}catch(e){toast(e.message)}}
function training(){if(!draft)return `<div class="section"><h3>Registo Express</h3><span class="pill red">⚡ Rápido</span></div><div class="card"><div class="field"><label>Escalão</label><select id="tg"><option>Benjamins</option><option>Traquinas</option><option>Todos</option></select></div><div class="muted" style="margin-bottom:11px">Todos começam como <b>Presentes · 4/4/4</b>. Altera só as exceções.</div><button class="btn btn-primary btn-block" onclick="startTraining()">⚡ Iniciar treino</button></div>`;
 const people=trainingPeople(),c=counts(people);return `<div class="section"><div><h3>Treino · ${draft.group}</h3><div class="muted">${fmt(draft.date)} · ${draft.time}</div></div><span class="pill red">⚡ Express</span></div><div class="express-summary"><div class="express-stat"><strong>${c.p}</strong><span>Presentes</span></div><div class="express-stat"><strong>${c.f}</strong><span>Faltas</span></div><div class="express-stat"><strong>${c.j}</strong><span>Justificadas</span></div><div class="express-stat"><strong>${c.c}</strong><span>Alterados</span></div></div><div class="list">${people.map(trainingCard).join('')}</div><div class="sticky-save"><button class="btn btn-primary btn-block" onclick="saveTraining()">Guardar treino · ${c.p} presentes</button></div>`}
function startTraining(){const n=new Date();draft={id:uid('t'),date:n.toISOString().slice(0,10),time:String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0'),group:$('tg').value,records:{}};trainingPeople().forEach(a=>rec(a.id));render()}
function trainingPeople(){return state.athletes.filter(a=>a.active&&(draft.group==='Todos'||a.group===draft.group||a.group==='Traquinas/Benjamins'))}
function rec(id){if(!draft.records[id])draft.records[id]={status:'Presente',attitude:4,effort:4,behavior:4,note:''};return draft.records[id]}
function counts(pp){let p=0,f=0,j=0,c=0;pp.forEach(a=>{const r=rec(a.id);r.status==='Presente'?p++:r.status==='Falta'?f++:j++;if(r.status==='Presente'&&(r.attitude!==4||r.effort!==4||r.behavior!==4))c++});return{p,f,j,c}}
function trainingCard(a){const r=rec(a.id),ch=r.status!=='Presente'||r.attitude!==4||r.effort!==4||r.behavior!==4;return `<div class="card express-athlete ${ch?'changed':''}"><div class="athlete">${avatar(a)}<div class="grow"><strong>${esc(a.name)}</strong><div class="muted">${esc(a.group)}</div></div></div><div class="attendance">${['Presente','Falta','Justificada'].map(s=>`<button class="${r.status===s?(s==='Presente'?'present':s==='Falta'?'absent':'justified'):''}" onclick="status('${a.id}','${s}')">${s==='Presente'?'✅':s==='Falta'?'❌':'🟡'} ${s}</button>`).join('')}</div>${r.status==='Presente'?`<div class="presets"><button class="${r.attitude===5&&r.effort===5&&r.behavior===5?'on':''}" onclick="preset('${a.id}',5)">🔥<span>Excelente</span></button><button class="${r.attitude===4&&r.effort===4&&r.behavior===4?'on':''}" onclick="preset('${a.id}',4)">👍<span>Bom</span></button><button class="${r.attitude===3&&r.effort===3&&r.behavior===3?'on':''}" onclick="preset('${a.id}',3)">⚠️<span>Atenção</span></button><button class="${r.behavior===2?'on':''}" onclick="behavior('${a.id}')">🚨<span>Comport.</span></button></div><button class="details-toggle" onclick="$('d-${a.id}').classList.toggle('open')">Ajustar individualmente ▾</button><div class="details" id="d-${a.id}">${[['attitude','Atitude'],['effort','Empenho'],['behavior','Comportamento']].map(([k,l])=>`<div class="metric"><div class="metric-head"><b>${l}</b><span>${r[k]}/5</span></div><div class="rating">${[1,2,3,4,5].map(n=>`<button class="${r[k]===n?'on':''}" onclick="rate('${a.id}','${k}',${n})">${n}</button>`).join('')}</div></div>`).join('')}<div class="field"><textarea placeholder="Observação opcional" onchange="rec('${a.id}').note=this.value">${esc(r.note)}</textarea></div></div>`:''}</div>`}
function status(id,s){rec(id).status=s;render()}function preset(id,n){Object.assign(rec(id),{status:'Presente',attitude:n,effort:n,behavior:n});render()}function behavior(id){rec(id).status='Presente';rec(id).behavior=2;render()}function rate(id,k,n){rec(id)[k]=n;render()}
async function saveTraining(){try{await api('saveTraining',{training:{id:draft.id,date:draft.date,time:draft.time,group:draft.group,records:trainingPeople().map(a=>({athleteId:a.id,...rec(a.id)}))}});draft=null;await refresh();view='dashboard';render();toast('Treino guardado')}catch(e){toast(e.message)}}
function dashboard(){const aa=state.athletes.filter(a=>a.active),rank=aa.map(a=>({...a,score:score(a)})).sort((a,b)=>b.score-a.score);return `<div class="section"><h3>Dashboard técnico</h3></div><div class="grid"><div class="card kpi"><span>Atletas</span><strong>${aa.length}</strong></div><div class="card kpi"><span>Treinos</span><strong>${state.trainings.length}</strong></div><div class="card kpi"><span>Assiduidade média</span><strong>${aa.length?Math.round(aa.reduce((s,a)=>s+attendancePct(a.id),0)/aa.length):0}%</strong></div><div class="card kpi"><span>Empenho médio</span><strong>${aa.length?(aa.reduce((s,a)=>s+avg(a.id,'effort'),0)/aa.length).toFixed(1):'0.0'}</strong></div></div><div class="section"><h3>Índice de treino</h3></div><div class="list">${rank.map((a,i)=>`<div class="card rank"><div class="rankno">${i+1}</div>${avatar(a)}<div class="grow"><strong>${esc(a.name)}</strong><div class="muted">${attendancePct(a.id)}% presença · Empenho ${avg(a.id,'effort').toFixed(1)}</div><div class="bar"><i style="width:${a.score}%"></i></div></div><div class="score">${a.score}</div></div>`).join('')}</div>`}
function callup(){return `<div class="section"><h3>Convocatória</h3></div><div class="card"><div class="field"><label>Adversário</label><input id="opp"></div><div class="form2"><div class="field"><label>Data</label><input id="gd" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Escalão</label><select id="gg"><option>Benjamins</option><option>Traquinas</option></select></div></div><div class="field"><label>N.º jogadores</label><input id="gn" type="number" value="12"></div><button class="btn btn-primary btn-block" onclick="suggest()">Gerar sugestão</button></div><div id="sug"></div>`}
function suggest(){const g=$('gg').value,n=Number($('gn').value||12),aa=state.athletes.filter(a=>a.active&&(a.group===g||a.group==='Traquinas/Benjamins')).map(a=>({...a,score:score(a)})).sort((a,b)=>b.score-a.score);$('sug').innerHTML=`<div class="section"><h3>Sugestão</h3></div><div class="list">${aa.map((a,i)=>`<div class="card athlete">${avatar(a)}<div class="grow"><strong>${esc(a.name)}</strong><div class="muted">Índice ${a.score}</div></div><span class="pill ${i<n?'green':''}">${i<n?'Convocar':'Reserva'}</span></div>`).join('')}</div>`}
function users(){if(!admin())return '<div class="admin-note">Acesso exclusivo ao Administrador.</div>';return `<div class="section"><h3>Utilizadores</h3><button class="btn btn-primary" onclick="userForm()">+ Adicionar</button></div><div class="list">${state.users.map(u=>`<div class="card athlete"><div class="avatar">${u.role==='admin'?'A':'T'}</div><div class="grow"><strong>${esc(u.name)}</strong><div class="muted">@${esc(u.username)} · ${u.role} · ${u.active?'Ativo':'Inativo'}</div></div><div class="actions"><button class="btn btn-small btn-ghost" onclick="userForm('${u.id}')">Editar</button><button class="btn btn-small btn-danger" onclick="toggleUser('${u.id}',${!u.active})">${u.active?'Desativar':'Ativar'}</button></div></div>`).join('')}</div>`}
function userForm(id=''){const u=id?state.users.find(x=>x.id===id):null;view='userForm';$('app').innerHTML=shell(`<div class="section"><h3>${u?'Editar':'Novo'} utilizador</h3></div><div class="card"><div class="field"><label>Nome</label><input id="un" value="${esc(u?.name||'')}"></div><div class="field"><label>Utilizador</label><input id="uu" value="${esc(u?.username||'')}"></div><div class="field"><label>PIN ${u?'(deixa vazio para manter)':''}</label><input id="up" type="password" inputmode="numeric"></div><div class="field"><label>Perfil</label><select id="ur"><option value="treinador" ${u?.role==='treinador'?'selected':''}>Treinador</option><option value="admin" ${u?.role==='admin'?'selected':''}>Administrador</option></select></div><button class="btn btn-primary btn-block" onclick="saveUser('${id}')">Guardar</button></div>`)}
async function saveUser(id){try{await api('saveUser',{target:{id,name:$('un').value.trim(),username:$('uu').value.trim(),pin:$('up').value,role:$('ur').value}});await refresh();view='users';render();toast('Utilizador guardado')}catch(e){toast(e.message)}}
async function toggleUser(id,active){try{await api('toggleUser',{id,active});await refresh();render()}catch(e){toast(e.message)}}
function render(){if(!user||!token){$('app').innerHTML=loginScreen();return}let b='';if(view==='home')b=home();else if(view==='athletes')b=athletes();else if(view==='training')b=training();else if(view==='dashboard')b=dashboard();else if(view==='callup')b=callup();else if(view==='users')b=users();else return;$('app').innerHTML=shell(b)}
(async()=>{if(user&&token){$('app').innerHTML='<div class="loading">A carregar GDR Formação 360…</div>';try{await refresh()}catch(e){logout();return}}render()})();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
