const C=window.GDR_CONFIG;
const KEY='gdr360-data-v1';
const seed={
  athletes:[
    {id:'a1',name:'Vasco Almanso',group:'Benjamins',active:true},{id:'a2',name:'António Medinas',group:'Benjamins',active:true},{id:'a3',name:'Bernardo Dimas',group:'Benjamins',active:true},{id:'a4',name:'Santiago Quebra',group:'Benjamins',active:true},{id:'a5',name:'Luís Galaio',group:'Traquinas',active:true},{id:'a6',name:'Mateus Machado',group:'Traquinas',active:true},{id:'a7',name:'Simão Candeias',group:'Traquinas',active:true},{id:'a8',name:'Vicente Tavares',group:'Traquinas/Benjamins',active:true}
  ],
  trainings:[],records:[],games:[],callups:[]
};
let db=load();let view='home';let trainingDraft=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function el(id){return document.getElementById(id)}
function initials(n){return n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function today(){return new Date().toISOString().slice(0,10)}
function fmt(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-PT')}
function uid(p){return p+Math.random().toString(36).slice(2,8)+Date.now().toString(36)}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function nav(){return `<nav class="nav">${[['home','⌂','Início'],['training','⚽','Treino'],['athletes','👥','Atletas'],['callup','📋','Convocar'],['dashboard','📊','Dashboard']].map(([v,i,t])=>`<button class="${view===v?'active':''}" onclick="go('${v}')"><span class="ico">${i}</span>${t}</button>`).join('')}</nav>`}
function shell(body){return `<div class="app"><header class="topbar"><div class="brand"><div class="logo">360</div><div><h1>${C.APP_NAME}</h1><small>${C.CLUB_NAME}</small></div></div></header><main class="content">${body}</main>${nav()}</div>`}
function go(v){view=v;trainingDraft=null;render()}
function render(){let b='';if(view==='home')b=home();if(view==='athletes')b=athletes();if(view==='training')b=training();if(view==='dashboard')b=dashboard();if(view==='callup')b=callup();el('app').innerHTML=shell(b)}
function attendancePct(aid){const r=db.records.filter(x=>x.athleteId===aid);if(!r.length)return 0;return Math.round(r.filter(x=>x.status==='Presente').length/r.length*100)}
function avg(aid,k){const r=db.records.filter(x=>x.athleteId===aid&&x.status==='Presente'&&x[k]);return r.length?(r.reduce((s,x)=>s+Number(x[k]),0)/r.length):0}
function home(){const active=db.athletes.filter(a=>a.active);const all=db.records;const pres=all.filter(r=>r.status==='Presente').length;const ap=all.length?Math.round(pres/all.length*100):0;return `<section class="hero"><h2>Olá, equipa técnica 👋</h2><p>Regista o treino em segundos e acompanha a evolução da formação.</p></section><div class="grid"><div class="card kpi"><span>Atletas ativos</span><strong>${active.length}</strong></div><div class="card kpi"><span>Treinos</span><strong>${db.trainings.length}</strong></div><div class="card kpi"><span>Assiduidade</span><strong>${ap}%</strong></div><div class="card kpi"><span>Jogos</span><strong>${db.games.length}</strong></div></div><div class="section-title"><h3>Ações rápidas</h3></div><div class="list"><button class="btn btn-primary btn-block" onclick="go('training')">⚽ Registar treino</button><button class="btn btn-secondary btn-block" onclick="go('callup')">📋 Preparar convocatória</button><button class="btn btn-secondary btn-block" onclick="go('athletes')">👥 Gerir atletas</button></div>`}
function athletes(){const list=db.athletes.filter(a=>a.active).map(a=>`<div class="card athlete"><div class="avatar">${initials(a.name)}</div><div class="grow"><strong>${a.name}</strong><div class="muted">${a.group} · ${attendancePct(a.id)}% presença</div></div><span class="pill red">${avg(a.id,'effort').toFixed(1) || '0.0'}</span></div>`).join('');return `<div class="section-title"><h3>Atletas</h3><button class="btn btn-primary" onclick="addAthlete()">+ Adicionar</button></div><div class="list">${list||'<div class="empty">Ainda não existem atletas.</div>'}</div>`}
function addAthlete(){const name=prompt('Nome do atleta:');if(!name)return;const group=prompt('Escalão: Traquinas, Benjamins ou Traquinas/Benjamins','Benjamins')||'Benjamins';db.athletes.push({id:uid('a'),name,group,active:true});save();render();toast('Atleta adicionado')}
function training(){if(!trainingDraft){return `<div class="section-title"><h3>Novo treino</h3></div><div class="card"><div class="form-row"><div class="field"><label>Data</label><input id="tdate" type="date" value="${today()}"></div><div class="field"><label>Escalão</label><select id="tgroup"><option>Benjamins</option><option>Traquinas</option><option>Todos</option></select></div></div><div class="field"><label>Hora</label><input id="ttime" type="time" value="${C.DEFAULT_TRAINING_TIME}"></div><button class="btn btn-primary btn-block" onclick="startTraining()">Começar registo</button></div>`}
const people=db.athletes.filter(a=>a.active&&(trainingDraft.group==='Todos'||a.group===trainingDraft.group||a.group==='Traquinas/Benjamins'));
return `<div class="section-title"><h3>${trainingDraft.group} · ${fmt(trainingDraft.date)}</h3></div><div class="toolbar"><button class="btn btn-ghost" onclick="setAll('Presente')">Todos presentes</button><button class="btn btn-ghost" onclick="setBase4()">Avaliação base 4</button></div><div class="list" style="margin-top:10px">${people.map(cardTraining).join('')}</div><div style="height:12px"></div><button class="btn btn-primary btn-block" onclick="saveTraining()">Guardar treino</button>`}
function startTraining(){trainingDraft={id:uid('t'),date:el('tdate').value,time:el('ttime').value,group:el('tgroup').value,records:{}};render()}
function ensureRec(id){if(!trainingDraft.records[id])trainingDraft.records[id]={status:'Presente',attitude:4,effort:4,behavior:4,note:''};return trainingDraft.records[id]}
function cardTraining(a){const r=ensureRec(a.id);return `<div class="card"><div class="athlete"><div class="avatar">${initials(a.name)}</div><div class="grow"><strong>${a.name}</strong><div class="muted">${a.group}</div></div></div><div class="attendance">${['Presente','Falta','Justificada'].map(s=>`<button class="${r.status===s?'sel-'+(s==='Presente'?'present':s==='Falta'?'absent':'justified'):''}" onclick="setStatus('${a.id}','${s}')">${s==='Presente'?'✅':s==='Falta'?'❌':'🟡'} ${s}</button>`).join('')}</div>${r.status==='Presente'?['attitude|Atitude','effort|Empenho','behavior|Comportamento'].map(z=>{const[k,l]=z.split('|');return `<div class="metric"><div class="metric-head"><b>${l}</b><span>${r[k]}/5</span></div><div class="rating">${[1,2,3,4,5].map(n=>`<button class="${Number(r[k])===n?'active':''}" onclick="rate('${a.id}','${k}',${n})">${n}</button>`).join('')}</div></div>`}).join(''):''}<div class="field"><textarea rows="2" placeholder="Observação opcional" onchange="note('${a.id}',this.value)">${r.note||''}</textarea></div></div>`}
function setStatus(id,s){ensureRec(id).status=s;render()}function rate(id,k,n){ensureRec(id)[k]=n;render()}function note(id,v){ensureRec(id).note=v}function setAll(s){Object.keys(trainingDraft.records).forEach(id=>trainingDraft.records[id].status=s);render()}function setBase4(){Object.keys(trainingDraft.records).forEach(id=>Object.assign(trainingDraft.records[id],{attitude:4,effort:4,behavior:4}));render()}
function saveTraining(){db.trainings.push({id:trainingDraft.id,date:trainingDraft.date,time:trainingDraft.time,group:trainingDraft.group});Object.entries(trainingDraft.records).forEach(([athleteId,r])=>db.records.push({id:uid('r'),trainingId:trainingDraft.id,athleteId,...r}));save();trainingDraft=null;view='dashboard';render();toast('Treino guardado')}
function scoreAthlete(a){const p=attendancePct(a.id);const e=avg(a.id,'effort')*20;const at=avg(a.id,'attitude')*20;const b=avg(a.id,'behavior')*20;return Math.round(p*.35+e*.30+at*.20+b*.15)}
function dashboard(){const active=db.athletes.filter(a=>a.active);const ranked=active.map(a=>({...a,score:scoreAthlete(a)})).sort((a,b)=>b.score-a.score);const ass=active.length?Math.round(active.reduce((s,a)=>s+attendancePct(a.id),0)/active.length):0;const emp=active.length?(active.reduce((s,a)=>s+avg(a.id,'effort'),0)/active.length).toFixed(1):'0.0';return `<div class="section-title"><h3>Dashboard técnico</h3></div><div class="grid"><div class="card kpi"><span>Assiduidade média</span><strong>${ass}%</strong></div><div class="card kpi"><span>Empenho médio</span><strong>${emp}</strong></div><div class="card kpi"><span>Treinos registados</span><strong>${db.trainings.length}</strong></div><div class="card kpi"><span>Atletas</span><strong>${active.length}</strong></div></div><div class="section-title"><h3>Índice de treino</h3></div><div class="list">${ranked.map((a,i)=>`<div class="card rank"><div class="rank-num">${i+1}</div><div class="grow"><strong>${a.name}</strong><div class="muted">${attendancePct(a.id)}% presença · Empenho ${avg(a.id,'effort').toFixed(1)}</div><div class="bar"><i style="width:${a.score}%"></i></div></div><div class="score">${a.score}</div></div>`).join('')}</div>`}
function callup(){return `<div class="section-title"><h3>Nova convocatória</h3></div><div class="card"><div class="form-row"><div class="field"><label>Adversário</label><input id="opp" placeholder="Ex.: CDR Salvadense"></div><div class="field"><label>Data</label><input id="gdate" type="date" value="${today()}"></div></div><div class="form-row"><div class="field"><label>Escalão</label><select id="ggroup"><option>Benjamins</option><option>Traquinas</option></select></div><div class="field"><label>N.º jogadores</label><input id="gnum" type="number" min="1" value="12"></div></div><button class="btn btn-primary btn-block" onclick="suggestCallup()">Gerar sugestão</button></div><div id="callupResult"></div>`}
function suggestCallup(){const group=el('ggroup').value,n=Number(el('gnum').value||12),opp=el('opp').value||'Adversário',date=el('gdate').value;const eligible=db.athletes.filter(a=>a.active&&(a.group===group||a.group==='Traquinas/Benjamins')).map(a=>({...a,score:scoreAthlete(a)})).sort((a,b)=>b.score-a.score);const selected=eligible.slice(0,n);el('callupResult').innerHTML=`<div class="section-title"><h3>Sugestão · ${opp}</h3><span class="pill">${fmt(date)}</span></div><div class="list">${eligible.map((a,i)=>`<div class="card athlete"><div class="avatar">${initials(a.name)}</div><div class="grow"><strong>${a.name}</strong><div class="muted">Índice ${a.score} · ${attendancePct(a.id)}% presença</div></div><span class="pill ${i<n?'green':''}">${i<n?'Convocar':'Reserva'}</span></div>`).join('')}</div><div style="height:12px"></div><button class="btn btn-primary btn-block" onclick='saveCallup(${JSON.stringify(JSON.stringify({opp,date,group,ids:selected.map(x=>x.id)}))})'>Guardar convocatória</button>`}
function saveCallup(json){db.callups.push({id:uid('c'),...JSON.parse(json)});save();toast('Convocatória guardada')}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
render();
